variable "IMAGE" {
  type = string
}

job "demo" {
  namespace   = "prod"
  datacenters = ["dc1"]
  type        = "service"

  # ---------------------------------------------------------------
  # edge: reverse proxy + cloudflare tunnel
  #
  # Pure bridge networking -- nothing bound to the host at all.
  # Traefik's routing config is generated by Nomad's own template
  # rendering (runs client-side, not over the task's network), using
  # nomadService to list every healthy frontend replica. Traefik just
  # watches that local file -- no network call to the Nomad API needed.
  # cloudflared shares this group's netns and always targets the fixed
  # localhost:80, so scaling frontend/backend never touches this group.
  # ---------------------------------------------------------------
  group "edge" {
    count = 1

    network {
      mode = "bridge"
    }

    task "traefik" {
      driver = "podman"

      config {
        image = "docker.io/library/traefik:v3.1"
        args = [
          "--entrypoints.web.address=:80",
          "--providers.file.filename=/local/dynamic.yml",
          "--providers.file.watch=true",
          "--log.level=INFO",
        ]
      }

      # Renders the full list of healthy frontend replicas into a
      # Traefik dynamic config file. Re-renders automatically whenever
      # instances are added/removed/rescheduled; Traefik's file
      # provider watch picks up the change live, no restart needed.
      template {
        data        = <<EOF
http:
  routers:
    demo-frontend:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: demo-frontend
  services:
    demo-frontend:
      loadBalancer:
        servers:
{{ range nomadService "demo-frontend" }}
          - url: "http://{{ .Address }}:{{ .Port }}"
{{ end }}
EOF
        destination = "local/dynamic.yml"
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }

    task "cloudflared" {
      driver = "podman"

      config {
        image = "docker.io/cloudflare/cloudflared:latest"
        args = [
          "tunnel",
          "--no-autoupdate",
          "run",
          "--token",
          "eyJhIjoiNTU4MGZmODNiMTRjN2YyYjVlZTdlMGQ1NGEzNDIyNmMiLCJ0IjoiNmE3YWM2MDktOWEyMy00NzU5LThjYjYtODUzZDkwY2QzOTgyIiwicyI6IllUY3lZbVZtTldFdE1ETTFaQzAwWkRjeExXRTRaREV0WXpReU1XSmxNV1JrWlRObCJ9",
        ]
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }

  # ---------------------------------------------------------------
  # group1: frontend -- scales independently via `count`
  # ---------------------------------------------------------------
  group "group1-frontend" {
    count = 1

    network {
      mode = "bridge"
    }

    service {
      name         = "demo-frontend"
      port         = 80
      provider     = "nomad"
      address_mode = "alloc"

      check {
        type         = "http"
        path         = "/"
        interval     = "10s"
        timeout      = "2s"
        address_mode = "alloc"
        port         = 80
      }
    }

    task "frontend" {
      driver = "podman"

      config {
        image = var.IMAGE
      }
# docker.io/library/nginx:alpine
      # Discover group2's address/port via Nomad's native service
      # discovery and drop it into a file the frontend task can read.
      template {
        data        = <<EOF
{{ range nomadService "demo-backend" }}
BACKEND_ADDR={{ .Address }}:{{ .Port }}
{{ end }}
EOF
        destination = "local/backend.env"
        env         = true
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }

  # ---------------------------------------------------------------
  # group2: backend -- also scales independently via `count`
  # ---------------------------------------------------------------
  group "group2-backend" {
    count = 1

    network {
      mode = "bridge"
    }

    service {
      name         = "demo-backend"
      port         = 80
      provider     = "nomad"
      address_mode = "alloc"

      check {
        type         = "http"
        path         = "/"
        interval     = "10s"
        timeout      = "2s"
        address_mode = "alloc"
        port         = 80
      }
    }

    task "backend" {
      driver = "podman"

      config {
        image = "docker.io/library/nginx:alpine"
      }

      resources {
        cpu    = 100
        memory = 128
      }
    }
  }
}
 